# Generated by Django 4.2.27 on 2026-01-16 12:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('texts', '0002_initial'),
        ('achievements', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='챌린지 날짜')),
                ('title', models.CharField(max_length=100, verbose_name='챌린지 제목')),
                ('description', models.TextField(verbose_name='챌린지 설명')),
                ('challenge_type', models.CharField(choices=[('speed', '속도 챌린지'), ('accuracy', '정확도 챌린지'), ('endurance', '지구력 챌린지'), ('special', '특별 챌린지')], default='speed', max_length=20, verbose_name='챌린지 유형')),
                ('difficulty', models.PositiveSmallIntegerField(choices=[(1, '쉬움'), (2, '보통'), (3, '어려움'), (4, '극한')], default=2, verbose_name='난이도')),
                ('target_wpm', models.PositiveIntegerField(blank=True, null=True, verbose_name='목표 WPM')),
                ('target_accuracy', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='목표 정확도 (%)')),
                ('target_sessions', models.PositiveIntegerField(blank=True, null=True, verbose_name='목표 세션 수')),
                ('target_time_minutes', models.PositiveIntegerField(blank=True, null=True, verbose_name='목표 시간 (분)')),
                ('reward_points', models.PositiveIntegerField(default=100, verbose_name='보상 포인트')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('reward_badge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='challenges', to='achievements.badge', verbose_name='보상 뱃지')),
                ('text_pack', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='texts.textpack', verbose_name='지정 문장팩')),
            ],
            options={
                'verbose_name': '데일리 챌린지',
                'verbose_name_plural': '데일리 챌린지들',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='UserChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('in_progress', '진행 중'), ('completed', '완료'), ('failed', '실패')], default='in_progress', max_length=20, verbose_name='상태')),
                ('current_wpm', models.PositiveIntegerField(blank=True, null=True, verbose_name='현재 WPM')),
                ('current_accuracy', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='현재 정확도 (%)')),
                ('current_sessions', models.PositiveIntegerField(default=0, verbose_name='현재 세션 수')),
                ('current_time_minutes', models.PositiveIntegerField(default=0, verbose_name='현재 시간 (분)')),
                ('reward_claimed', models.BooleanField(default=False, verbose_name='보상 수령 여부')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='시작 시각')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='완료 시각')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='challenges.dailychallenge', verbose_name='챌린지')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenges', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '사용자 챌린지',
                'verbose_name_plural': '사용자 챌린지들',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='idx_uc_user_status'), models.Index(fields=['challenge', 'status'], name='idx_uc_challenge_status')],
            },
        ),
        migrations.AddConstraint(
            model_name='userchallenge',
            constraint=models.UniqueConstraint(fields=('user', 'challenge'), name='uq_user_challenge'),
        ),
        migrations.AddIndex(
            model_name='dailychallenge',
            index=models.Index(fields=['-date', 'is_active'], name='idx_challenge_date_active'),
        ),
    ]
