# Generated by Django 4.2.28 on 2026-02-13 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_session_id', models.CharField(max_length=100, verbose_name='게스트 세션 ID')),
                ('status', models.CharField(choices=[('in_progress', '진행 중'), ('completed', '완료'), ('failed', '실패')], default='in_progress', max_length=20, verbose_name='상태')),
                ('current_wpm', models.PositiveIntegerField(blank=True, null=True, verbose_name='현재 WPM')),
                ('current_accuracy', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='현재 정확도 (%)')),
                ('current_sessions', models.PositiveIntegerField(default=0, verbose_name='현재 세션 수')),
                ('current_time_minutes', models.PositiveIntegerField(default=0, verbose_name='현재 시간 (분)')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='시작 시각')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='완료 시각')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guest_participants', to='challenges.dailychallenge', verbose_name='챌린지')),
            ],
            options={
                'verbose_name': '익명 챌린지',
                'verbose_name_plural': '익명 챌린지들',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['guest_session_id', 'status'], name='idx_cc_guest_status'), models.Index(fields=['challenge', 'status'], name='idx_cc_challenge_status')],
            },
        ),
        migrations.AddConstraint(
            model_name='clientchallenge',
            constraint=models.UniqueConstraint(fields=('guest_session_id', 'challenge'), name='uq_client_challenge'),
        ),
    ]
