# Generated by Django 4.2.27 on 2026-01-16 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('texts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_ms', models.PositiveIntegerField(help_text='세션 시작 기준 밀리초', verbose_name='시간 오프셋 (ms)')),
                ('expected', models.CharField(blank=True, max_length=5, verbose_name='기대 문자')),
                ('typed', models.CharField(blank=True, max_length=5, verbose_name='입력 문자')),
                ('is_correct', models.BooleanField(db_index=True, default=True, verbose_name='정오타')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='문장 내 위치')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
            ],
            options={
                'verbose_name': '타이핑 이벤트',
                'verbose_name_plural': '타이핑 이벤트들',
                'ordering': ['session', 't_ms'],
            },
        ),
        migrations.CreateModel(
            name='TypingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('practice', '연습'), ('challenge', '챌린지'), ('ranked', '랭킹전')], db_index=True, default='practice', max_length=20, verbose_name='모드')),
                ('language', models.CharField(choices=[('ko', '한글'), ('en', '영어')], db_index=True, default='ko', max_length=10, verbose_name='언어')),
                ('text_content', models.TextField(help_text='원본 문장 삭제 시에도 기록 유지를 위해 저장', verbose_name='연습한 문장 내용')),
                ('started_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='시작 시각')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='종료 시각')),
                ('duration_ms', models.PositiveIntegerField(default=0, verbose_name='소요 시간 (ms)')),
                ('input_length', models.PositiveIntegerField(default=0, verbose_name='총 입력 길이')),
                ('correct_length', models.PositiveIntegerField(default=0, verbose_name='정확 입력 길이')),
                ('error_count', models.PositiveIntegerField(default=0, verbose_name='오타 수')),
                ('accuracy', models.DecimalField(db_index=True, decimal_places=2, default=0, max_digits=5, verbose_name='정확도 (%)')),
                ('wpm', models.DecimalField(db_index=True, decimal_places=2, default=0, max_digits=6, verbose_name='WPM (분당 단어수)')),
                ('cpm', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='CPM (분당 문자수)')),
                ('metadata', models.JSONField(blank=True, help_text='기기/브라우저/키보드 등 확장 정보', null=True, verbose_name='메타데이터')),
                ('guest_session_id', models.CharField(blank=True, help_text='비로그인 사용자 식별용', max_length=100, verbose_name='게스트 세션 ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('pack', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='texts.textpack', verbose_name='문장팩')),
                ('text_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='texts.textitem', verbose_name='연습 문장')),
            ],
            options={
                'verbose_name': '타자 세션',
                'verbose_name_plural': '타자 세션들',
                'ordering': ['-started_at'],
            },
        ),
    ]
