# Generated by Django 4.2.27 on 2026-01-16 12:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('typing_sessions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='typingsession',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='typing_sessions', to=settings.AUTH_USER_MODEL, verbose_name='사용자'),
        ),
        migrations.AddField(
            model_name='typingevent',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='typing_sessions.typingsession', verbose_name='세션'),
        ),
        migrations.AddIndex(
            model_name='typingsession',
            index=models.Index(fields=['user', '-started_at'], name='idx_session_user_started'),
        ),
        migrations.AddIndex(
            model_name='typingsession',
            index=models.Index(fields=['mode', 'language', '-started_at'], name='idx_session_mode_lang'),
        ),
        migrations.AddIndex(
            model_name='typingsession',
            index=models.Index(fields=['pack', '-started_at'], name='idx_session_pack_started'),
        ),
        migrations.AddConstraint(
            model_name='typingsession',
            constraint=models.CheckConstraint(check=models.Q(('accuracy__gte', 0), ('accuracy__lte', 100)), name='chk_accuracy_range'),
        ),
        migrations.AddConstraint(
            model_name='typingsession',
            constraint=models.CheckConstraint(check=models.Q(('wpm__gte', 0)), name='chk_wpm_positive'),
        ),
        migrations.AddConstraint(
            model_name='typingsession',
            constraint=models.CheckConstraint(check=models.Q(('error_count__gte', 0)), name='chk_error_positive'),
        ),
        migrations.AddIndex(
            model_name='typingevent',
            index=models.Index(fields=['session', 't_ms'], name='idx_event_session_t'),
        ),
        migrations.AddIndex(
            model_name='typingevent',
            index=models.Index(fields=['session', 'is_correct'], name='idx_event_session_correct'),
        ),
    ]
