# Generated by Django 4.2.27 on 2026-01-16 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_type', models.CharField(choices=[('time', '연습 시간 (분)'), ('sessions', '세션 수'), ('chars', '입력 문자수')], default='time', max_length=20, verbose_name='목표 유형')),
                ('target_value', models.PositiveIntegerField(default=30, help_text='시간(분), 세션수, 문자수 등', verbose_name='목표값')),
                ('language', models.CharField(choices=[('ko', '한글'), ('en', '영어'), ('all', '전체')], default='all', max_length=10, verbose_name='대상 언어')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'verbose_name': '사용자 목표',
                'verbose_name_plural': '사용자 목표들',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserStreak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_streak', models.PositiveIntegerField(default=0, verbose_name='현재 스트릭')),
                ('longest_streak', models.PositiveIntegerField(default=0, verbose_name='최장 스트릭')),
                ('last_active_date', models.DateField(blank=True, null=True, verbose_name='마지막 활동일')),
                ('streak_start_date', models.DateField(blank=True, null=True, verbose_name='스트릭 시작일')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'verbose_name': '사용자 스트릭',
                'verbose_name_plural': '사용자 스트릭들',
            },
        ),
    ]
