# Generated by Django 4.2.28 on 2026-02-13 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientStreak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_session_id', models.CharField(max_length=100, unique=True, verbose_name='게스트 세션 ID')),
                ('current_streak', models.PositiveIntegerField(default=0, verbose_name='현재 스트릭')),
                ('longest_streak', models.PositiveIntegerField(default=0, verbose_name='최장 스트릭')),
                ('last_active_date', models.DateField(blank=True, null=True, verbose_name='마지막 활동일')),
                ('streak_start_date', models.DateField(blank=True, null=True, verbose_name='스트릭 시작일')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'verbose_name': '익명 스트릭',
                'verbose_name_plural': '익명 스트릭들',
            },
        ),
    ]
