# Generated by Django 4.2.27 on 2026-01-16 12:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='시스템에서 사용하는 고유 코드', max_length=50, unique=True, verbose_name='코드')),
                ('name', models.CharField(max_length=100, verbose_name='뱃지 이름')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('icon', models.CharField(default='🏆', max_length=50, verbose_name='아이콘')),
                ('category', models.CharField(choices=[('speed', '속도'), ('accuracy', '정확도'), ('streak', '연속일'), ('challenge', '챌린지'), ('milestone', '마일스톤'), ('special', '특별')], default='milestone', max_length=20, verbose_name='카테고리')),
                ('rarity', models.PositiveSmallIntegerField(choices=[(1, '일반'), (2, '희귀'), (3, '영웅'), (4, '전설')], default=1, verbose_name='희귀도')),
                ('condition_type', models.CharField(blank=True, help_text='wpm_reach, accuracy_reach, streak_reach, sessions_complete 등', max_length=50, verbose_name='조건 유형')),
                ('condition_value', models.PositiveIntegerField(blank=True, null=True, verbose_name='조건 값')),
                ('reward_points', models.PositiveIntegerField(default=50, verbose_name='보상 포인트')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화')),
                ('is_secret', models.BooleanField(default=False, help_text='획득 전까지 숨김', verbose_name='시크릿 뱃지')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='정렬 순서')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'verbose_name': '뱃지',
                'verbose_name_plural': '뱃지들',
                'ordering': ['order', 'category', 'rarity'],
            },
        ),
        migrations.CreateModel(
            name='UserLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveIntegerField(default=1, verbose_name='레벨')),
                ('experience', models.PositiveIntegerField(default=0, verbose_name='경험치')),
                ('total_points', models.PositiveIntegerField(default=0, verbose_name='총 포인트')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='level', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '사용자 레벨',
                'verbose_name_plural': '사용자 레벨들',
            },
        ),
        migrations.CreateModel(
            name='UserBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_at', models.DateTimeField(auto_now_add=True, verbose_name='획득 시각')),
                ('is_featured', models.BooleanField(default=False, help_text='프로필에 표시할 대표 뱃지', verbose_name='대표 뱃지')),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owners', to='achievements.badge', verbose_name='뱃지')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '사용자 뱃지',
                'verbose_name_plural': '사용자 뱃지들',
                'ordering': ['-earned_at'],
            },
        ),
        migrations.AddIndex(
            model_name='badge',
            index=models.Index(fields=['category', 'is_active'], name='idx_badge_category'),
        ),
        migrations.AddIndex(
            model_name='badge',
            index=models.Index(fields=['condition_type'], name='idx_badge_condition'),
        ),
        migrations.AddIndex(
            model_name='userbadge',
            index=models.Index(fields=['user', '-earned_at'], name='idx_ub_user_earned'),
        ),
        migrations.AddConstraint(
            model_name='userbadge',
            constraint=models.UniqueConstraint(fields=('user', 'badge'), name='uq_user_badge'),
        ),
    ]
