# Generated by Django 4.2.27 on 2026-01-16 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveIntegerField(db_index=True, verbose_name='순위')),
                ('score_wpm', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='평균 WPM')),
                ('score_accuracy', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='평균 정확도 (%)')),
                ('session_count', models.PositiveIntegerField(default=0, verbose_name='세션 수')),
                ('best_wpm', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='최고 WPM')),
                ('total_duration_ms', models.BigIntegerField(default=0, verbose_name='총 연습 시간 (ms)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'verbose_name': '랭킹 엔트리',
                'verbose_name_plural': '랭킹 엔트리들',
                'ordering': ['rank'],
            },
        ),
        migrations.CreateModel(
            name='Snapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(choices=[('daily', '일간'), ('weekly', '주간'), ('monthly', '월간')], db_index=True, default='weekly', max_length=10, verbose_name='기간')),
                ('start_date', models.DateField(db_index=True, verbose_name='기간 시작')),
                ('end_date', models.DateField(verbose_name='기간 끝')),
                ('mode', models.CharField(choices=[('practice', '연습'), ('ranked', '랭킹전'), ('all', '전체')], db_index=True, default='all', max_length=20, verbose_name='모드')),
                ('language', models.CharField(choices=[('ko', '한글'), ('en', '영어'), ('all', '전체')], db_index=True, default='all', max_length=10, verbose_name='언어')),
                ('generated_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 시각')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'verbose_name': '랭킹 스냅샷',
                'verbose_name_plural': '랭킹 스냅샷들',
                'ordering': ['-generated_at'],
                'indexes': [models.Index(fields=['period', '-start_date'], name='idx_snapshot_period_start'), models.Index(fields=['language', 'period', '-start_date'], name='idx_snapshot_lang_period')],
            },
        ),
        migrations.AddConstraint(
            model_name='snapshot',
            constraint=models.UniqueConstraint(fields=('period', 'start_date', 'end_date', 'mode', 'language'), name='uq_snapshot_period'),
        ),
        migrations.AddField(
            model_name='entry',
            name='snapshot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='leaderboard.snapshot', verbose_name='스냅샷'),
        ),
    ]
