# Generated by Django 4.2.27 on 2026-01-16 12:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leaderboard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard_entries', to=settings.AUTH_USER_MODEL, verbose_name='사용자'),
        ),
        migrations.AddIndex(
            model_name='entry',
            index=models.Index(fields=['snapshot', 'rank'], name='idx_entry_snapshot_rank'),
        ),
        migrations.AddIndex(
            model_name='entry',
            index=models.Index(fields=['user', '-created_at'], name='idx_entry_user_created'),
        ),
        migrations.AddConstraint(
            model_name='entry',
            constraint=models.UniqueConstraint(fields=('snapshot', 'user'), name='uq_entry_snapshot_user'),
        ),
        migrations.AddConstraint(
            model_name='entry',
            constraint=models.UniqueConstraint(fields=('snapshot', 'rank'), name='uq_entry_snapshot_rank'),
        ),
    ]
