# Generated by Django 4.2.28 on 2026-02-13 06:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leaderboard', '0002_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='entry',
            name='uq_entry_snapshot_user',
        ),
        migrations.AddField(
            model_name='entry',
            name='display_name',
            field=models.CharField(default='Guest', help_text='랭킹에 표시되는 이름', max_length=50, verbose_name='표시 이름'),
        ),
        migrations.AddField(
            model_name='entry',
            name='guest_session_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100, verbose_name='게스트 세션 ID'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard_entries', to=settings.AUTH_USER_MODEL, verbose_name='사용자'),
        ),
        migrations.AddIndex(
            model_name='entry',
            index=models.Index(fields=['guest_session_id', '-created_at'], name='idx_entry_guest_created'),
        ),
    ]
