# Generated by Django 4.2.27 on 2026-01-16 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Asia/Seoul 기준', verbose_name='날짜')),
                ('language', models.CharField(choices=[('ko', '한글'), ('en', '영어')], default='ko', max_length=10, verbose_name='언어')),
                ('total_sessions', models.PositiveIntegerField(default=0, verbose_name='세션 수')),
                ('total_duration_ms', models.BigIntegerField(default=0, verbose_name='총 연습 시간 (ms)')),
                ('avg_wpm', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='평균 WPM')),
                ('avg_accuracy', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='평균 정확도 (%)')),
                ('best_wpm', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='최고 WPM')),
                ('best_accuracy', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='최고 정확도 (%)')),
                ('total_chars', models.PositiveIntegerField(default=0, verbose_name='총 입력 문자수')),
                ('total_errors', models.PositiveIntegerField(default=0, verbose_name='총 오류 수')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'verbose_name': '일일 통계',
                'verbose_name_plural': '일일 통계들',
                'ordering': ['-date'],
            },
        ),
    ]
