# Generated by Django 4.2.27 on 2026-01-16 12:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stats', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userdaily',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_stats', to=settings.AUTH_USER_MODEL, verbose_name='사용자'),
        ),
        migrations.AddIndex(
            model_name='userdaily',
            index=models.Index(fields=['user', '-date'], name='idx_userdaily_user_date'),
        ),
        migrations.AddIndex(
            model_name='userdaily',
            index=models.Index(fields=['-date', 'language'], name='idx_userdaily_date_lang'),
        ),
        migrations.AddConstraint(
            model_name='userdaily',
            constraint=models.UniqueConstraint(fields=('user', 'date', 'language'), name='uq_user_date_language'),
        ),
    ]
