# Generated by Django 4.2.27 on 2026-01-16 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TextItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='문장 내용')),
                ('length', models.PositiveIntegerField(db_index=True, default=0, help_text='난이도/추천/통계용', verbose_name='글자 수')),
                ('punctuation_level', models.PositiveSmallIntegerField(default=0, help_text='특수문자/기호 포함 정도 (0-5)', verbose_name='기호 난이도')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='활성화')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='팩 내 순서')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'verbose_name': '연습 문장',
                'verbose_name_plural': '연습 문장들',
                'ordering': ['pack', 'order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TextPack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=100, verbose_name='문장팩 이름')),
                ('language', models.CharField(choices=[('ko', '한글'), ('en', '영어')], db_index=True, default='ko', max_length=10, verbose_name='언어')),
                ('difficulty', models.PositiveSmallIntegerField(db_index=True, default=3, help_text='1: 매우 쉬움, 5: 매우 어려움', verbose_name='난이도 (1-5)')),
                ('source', models.CharField(blank=True, choices=[('admin', '관리자'), ('user', '사용자'), ('import', '가져오기')], default='admin', max_length=50, verbose_name='출처')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='노출 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'verbose_name': '문장팩',
                'verbose_name_plural': '문장팩들',
                'ordering': ['language', 'difficulty', '-created_at'],
            },
        ),
    ]
