# Generated by Django 4.2.27 on 2026-01-16 12:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('texts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='textpack',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_packs', to=settings.AUTH_USER_MODEL, verbose_name='생성자'),
        ),
        migrations.AddField(
            model_name='textitem',
            name='pack',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='texts.textpack', verbose_name='소속 문장팩'),
        ),
        migrations.AddIndex(
            model_name='textpack',
            index=models.Index(fields=['language', 'is_active', 'difficulty'], name='idx_pack_lang_active_diff'),
        ),
        migrations.AddIndex(
            model_name='textitem',
            index=models.Index(fields=['pack', 'is_active'], name='idx_item_pack_active'),
        ),
        migrations.AddIndex(
            model_name='textitem',
            index=models.Index(fields=['pack', 'order'], name='idx_item_pack_order'),
        ),
    ]
