# Generated by Django 4.2.27 on 2026-02-06 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texts', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='textpack',
            options={'ordering': ['language', 'kind', 'difficulty', '-created_at'], 'verbose_name': '문장팩', 'verbose_name_plural': '문장팩들'},
        ),
        migrations.AddField(
            model_name='textitem',
            name='import_batch_id',
            field=models.CharField(blank=True, db_index=True, max_length=50, verbose_name='배치 ID'),
        ),
        migrations.AddField(
            model_name='textitem',
            name='normalized_content',
            field=models.TextField(blank=True, help_text='중복 검사용 정규화된 텍스트', verbose_name='정규화된 내용'),
        ),
        migrations.AddField(
            model_name='textitem',
            name='source_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='출처명'),
        ),
        migrations.AddField(
            model_name='textpack',
            name='code',
            field=models.CharField(blank=True, help_text='예: ko-word-daily-1', max_length=50, null=True, unique=True, verbose_name='팩 코드'),
        ),
        migrations.AddField(
            model_name='textpack',
            name='kind',
            field=models.CharField(choices=[('word', '단어'), ('short', '짧은글')], db_index=True, default='word', max_length=10, verbose_name='유형'),
        ),
        migrations.AddField(
            model_name='textpack',
            name='theme',
            field=models.CharField(choices=[('daily', '일반'), ('proverb', '속담')], db_index=True, default='daily', max_length=20, verbose_name='테마'),
        ),
        migrations.AlterField(
            model_name='textpack',
            name='difficulty',
            field=models.PositiveSmallIntegerField(db_index=True, default=1, help_text='1: 초급, 2: 중급, 3: 고급', verbose_name='난이도 (1-3)'),
        ),
        migrations.AddIndex(
            model_name='textitem',
            index=models.Index(fields=['import_batch_id'], name='idx_item_batch'),
        ),
        migrations.AddIndex(
            model_name='textpack',
            index=models.Index(fields=['language', 'kind', 'theme', 'difficulty', 'is_active'], name='idx_pack_practice'),
        ),
        # UniqueConstraint를 0005로 이동 (데이터 정규화 후)
    ]
