# Generated by Django 4.2.28 on 2026-02-13 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('guest_session_id', models.CharField(help_text='프론트엔드에서 생성한 익명 식별자 (guest_{timestamp}_{random})', max_length=50, primary_key=True, serialize=False)),
                ('nickname', models.CharField(blank=True, help_text='표시 이름 (기본: 익명-XXXX)', max_length=24, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('ua_hash', models.CharField(blank=True, help_text='User-Agent 해시 (선택)', max_length=64, null=True)),
                ('meta', models.JSONField(blank=True, default=dict, help_text='추가 메타 정보', null=True)),
            ],
            options={
                'verbose_name': '클라이언트',
                'verbose_name_plural': '클라이언트',
                'db_table': 'devices_client',
            },
        ),
    ]
